"""Generate filled demo pages from the 6 templates so we can preview them visually.
Outputs to site/template-demos/ (noindex, not in sitemap).
"""
from pathlib import Path
import re

TEMPLATES = Path(__file__).resolve().parents[1] / "outputs/templates"
SITE = Path(__file__).resolve().parents[1] / "site"
DEMO_DIR = SITE / "template-demos"
DEMO_DIR.mkdir(exist_ok=True)

def fill(template_path, replacements):
    html = template_path.read_text(encoding="utf-8")
    for k, v in replacements.items():
        html = html.replace("{{" + k + "}}", v)
    # Inject noindex
    html = html.replace('<link rel="canonical"', '<meta name="robots" content="noindex,nofollow">\n<link rel="canonical"', 1)
    return html

# ─── BEST-OF DEMO ───────────────────────────────────────────────────────────
best_of_data = {
    "PAGE_TITLE": "Best CRM Software 2026: Ranked &amp; Reviewed",
    "HERO_LEAD": "We compared 24 CRM platforms on published pricing, plan limits, and documented features. Here's how they stack up.",
    "META_DESCRIPTION": "We compared 24 CRM platforms on published pricing and plan limits. Here are the 6 best CRM tools of 2026 — ranked by real value, not vendor payments.",
    "CANONICAL_URL": "pages/best-crm-software-2026",
    "VERIFIED_DATE": "June 2026",
    "STAT_1_NUM": "24", "STAT_1_LABEL": "CRMs tested",
    "STAT_2_NUM": "47", "STAT_2_LABEL": "Data points",
    "STAT_3_NUM": "312", "STAT_3_LABEL": "Buyers surveyed",
    "STAT_4_NUM": "6", "STAT_4_LABEL": "Final picks",
    "CATEGORY": "CRM",
    "STICKY_CTA_TEXT": "Best CRM Software 2026 — Build your personalised shortlist in 2 minutes.",
    # ── Tool 1: HubSpot ──
    "TOOL_1_NAME": "HubSpot CRM", "TOOL_1_SCORE": "9.1", "TOOL_1_CROWN_TEXT": "⭐ Best Overall 2026",
    "TOOL_1_VERDICT": "Best Overall", "TOOL_1_VERDICT_CLASS": "v-best",
    "TOOL_1_RING_CLASS": "sr-gold", "TOOL_1_SCORE_OFFSET": "20.0",
    "TOOL_1_TAGLINE": "The most complete CRM for growing teams — unlimited free contacts, an intuitive interface, and a sales-marketing-service flywheel that genuinely works together.",
    "TOOL_1_LOGO_URL": "https://cdn.simpleicons.org/hubspot/ff7a59",
    "TOOL_1_VALUE_PCT": "93", "TOOL_1_VALUE_SCORE": "9.3",
    "TOOL_1_EASE_PCT": "96", "TOOL_1_EASE_SCORE": "9.6",
    "TOOL_1_FEATURES_PCT": "87", "TOOL_1_FEATURES_SCORE": "8.7",
    "TOOL_1_INT_PCT": "98", "TOOL_1_INT_SCORE": "9.8",
    "TOOL_1_SUPPORT_PCT": "88", "TOOL_1_SUPPORT_SCORE": "8.8",
    "TOOL_1_PRO_1": "Generous free CRM — unlimited contacts, no seat limit",
    "TOOL_1_PRO_2": " native integrations out of the box",
    "TOOL_1_PRO_3": "Sales, marketing &amp; service share one data layer",
    "TOOL_1_CON_1": "Advanced features locked behind paid Hubs",
    "TOOL_1_CON_2": "Pricing jumps sharply above 5 paid users",
    "TOOL_1_PRICE_LINE": "Free", "TOOL_1_PRICE_NOTE": "Paid plans from $15/user/mo",
    "TOOL_1_GO_LINK": "/go/hubspot-crm",
    # ── Tool 2: Salesforce ──
    "TOOL_2_NAME": "Salesforce", "TOOL_2_SCORE": "8.4",
    "TOOL_2_VERDICT": "Best Enterprise", "TOOL_2_VERDICT_CLASS": "v-ent",
    "TOOL_2_RING_CLASS": "sr-silver", "TOOL_2_SCORE_OFFSET": "29.2",
    "TOOL_2_TAGLINE": "The gold standard for complex enterprise sales. Infinitely customisable — but demands a serious implementation budget and dedicated admin resources.",
    "TOOL_2_LOGO_URL": "https://cdn.simpleicons.org/salesforce/00a1e0",
    "TOOL_2_VALUE_PCT": "64", "TOOL_2_VALUE_SCORE": "6.4",
    "TOOL_2_EASE_PCT": "60", "TOOL_2_EASE_SCORE": "6.0",
    "TOOL_2_FEATURES_PCT": "99", "TOOL_2_FEATURES_SCORE": "9.9",
    "TOOL_2_INT_PCT": "99", "TOOL_2_INT_SCORE": "9.9",
    "TOOL_2_SUPPORT_PCT": "79", "TOOL_2_SUPPORT_SCORE": "7.9",
    "TOOL_2_PRO_1": "Unmatched customisation depth &amp; scalability",
    "TOOL_2_PRO_2": "Best-in-class forecasting &amp; pipeline analytics",
    "TOOL_2_PRO_3": "Vast AppExchange partner ecosystem",
    "TOOL_2_CON_1": "True TCO is 2–3× the licence cost",
    "TOOL_2_CON_2": "Needs a full-time admin to unlock its value",
    "TOOL_2_PRICE_LINE": "$25/user/mo", "TOOL_2_PRICE_NOTE": "⚠ Hidden fees are common",
    "TOOL_2_GO_LINK": "/go/salesforce",
    # ── Tool 3: Pipedrive ──
    "TOOL_3_NAME": "Pipedrive", "TOOL_3_SCORE": "8.0",
    "TOOL_3_VERDICT": "Best for Sales Teams", "TOOL_3_VERDICT_CLASS": "v-sales",
    "TOOL_3_RING_CLASS": "sr-bronze", "TOOL_3_SCORE_OFFSET": "36.4",
    "TOOL_3_TAGLINE": "Pipeline-first CRM built by salespeople. Superb deal tracking, lightweight admin overhead, completely transparent pricing.",
    "TOOL_3_LOGO_URL": "https://cdn.simpleicons.org/pipedrive/1a73e8",
    "TOOL_3_VALUE_PCT": "88", "TOOL_3_VALUE_SCORE": "8.8",
    "TOOL_3_EASE_PCT": "93", "TOOL_3_EASE_SCORE": "9.3",
    "TOOL_3_FEATURES_PCT": "73", "TOOL_3_FEATURES_SCORE": "7.3",
    "TOOL_3_INT_PCT": "80", "TOOL_3_INT_SCORE": "8.0",
    "TOOL_3_SUPPORT_PCT": "77", "TOOL_3_SUPPORT_SCORE": "7.7",
    "TOOL_3_PRO_1": "Drag-and-drop pipeline view is best in class",
    "TOOL_3_PRO_2": "Minimal setup — useful from day one",
    "TOOL_3_PRO_3": "Flat, transparent pricing per user",
    "TOOL_3_CON_1": "Marketing automation is weak vs. HubSpot",
    "TOOL_3_CON_2": "Custom reporting locked to higher tiers",
    "TOOL_3_PRICE_LINE": "$14/user/mo", "TOOL_3_PRICE_NOTE": "30-day free trial",
    "TOOL_3_GO_LINK": "/go/pipedrive",
    # ── Tool 4: Monday CRM ──
    "TOOL_4_NAME": "Monday CRM", "TOOL_4_SCORE": "7.6",
    "TOOL_4_VERDICT": "Best Visual Workflow", "TOOL_4_VERDICT_CLASS": "v-visual",
    "TOOL_4_RING_CLASS": "sr-pink", "TOOL_4_SCORE_OFFSET": "43.7",
    "TOOL_4_TAGLINE": "Highly visual, no-code CRM on top of Monday's work OS. Perfect if your team already lives in Monday.",
    "TOOL_4_LOGO_URL": "https://cdn.simpleicons.org/monday/f62b54",
    "TOOL_4_VALUE_PCT": "74", "TOOL_4_VALUE_SCORE": "7.4",
    "TOOL_4_EASE_PCT": "86", "TOOL_4_EASE_SCORE": "8.6",
    "TOOL_4_FEATURES_PCT": "72", "TOOL_4_FEATURES_SCORE": "7.2",
    "TOOL_4_INT_PCT": "84", "TOOL_4_INT_SCORE": "8.4",
    "TOOL_4_SUPPORT_PCT": "76", "TOOL_4_SUPPORT_SCORE": "7.6",
    "TOOL_4_PRO_1": "Extremely flexible no-code customisation",
    "TOOL_4_PRO_2": "Unified CRM + project management surface",
    "TOOL_4_PRO_3": "Visual boards work well for non-sales teams",
    "TOOL_4_CON_1": "3-seat minimum on all paid plans",
    "TOOL_4_CON_2": "Dedicated CRM depth thinner than HubSpot",
    "TOOL_4_PRICE_LINE": "$12/seat/mo", "TOOL_4_PRICE_NOTE": "14-day free trial",
    "TOOL_4_GO_LINK": "/go/monday",
    # ── Tool 5: Zoho ──
    "TOOL_5_NAME": "Zoho CRM", "TOOL_5_SCORE": "7.2",
    "TOOL_5_VERDICT": "Best Value", "TOOL_5_VERDICT_CLASS": "v-value",
    "TOOL_5_RING_CLASS": "sr-pink", "TOOL_5_SCORE_OFFSET": "51.0",
    "TOOL_5_TAGLINE": "Enterprise-grade features at SMB pricing. Zia AI, custom modules, multi-channel engagement — an underrated powerhouse.",
    "TOOL_5_LOGO_URL": "https://cdn.simpleicons.org/zoho/e42527",
    "TOOL_5_VALUE_PCT": "97", "TOOL_5_VALUE_SCORE": "9.7",
    "TOOL_5_EASE_PCT": "63", "TOOL_5_EASE_SCORE": "6.3",
    "TOOL_5_FEATURES_PCT": "89", "TOOL_5_FEATURES_SCORE": "8.9",
    "TOOL_5_INT_PCT": "78", "TOOL_5_INT_SCORE": "7.8",
    "TOOL_5_SUPPORT_PCT": "69", "TOOL_5_SUPPORT_SCORE": "6.9",
    "TOOL_5_PRO_1": "Outstanding feature-per-dollar ratio",
    "TOOL_5_PRO_2": "Zia AI for deal predictions &amp; sentiment scoring",
    "TOOL_5_PRO_3": "Deeply customisable pipeline stages",
    "TOOL_5_CON_1": "UI feels dated compared to HubSpot",
    "TOOL_5_CON_2": "Support quality inconsistent on lower plans",
    "TOOL_5_PRICE_LINE": "Free / $14/user", "TOOL_5_PRICE_NOTE": "Free up to 3 users",
    "TOOL_5_GO_LINK": "/go/zoho-crm",
    # ── Tool 6: Freshsales ──
    "TOOL_6_NAME": "Freshsales", "TOOL_6_SCORE": "6.8",
    "TOOL_6_VERDICT": "Best for SMBs", "TOOL_6_VERDICT_CLASS": "v-smb",
    "TOOL_6_RING_CLASS": "sr-pink", "TOOL_6_SCORE_OFFSET": "58.3",
    "TOOL_6_TAGLINE": "Freddy AI, built-in phone &amp; email sequencing, and a forever-free plan make Freshsales the sharpest entry-level pick.",
    "TOOL_6_LOGO_URL": "https://cdn.simpleicons.org/freshworks/ffffff",
    "TOOL_6_VALUE_PCT": "90", "TOOL_6_VALUE_SCORE": "9.0",
    "TOOL_6_EASE_PCT": "83", "TOOL_6_EASE_SCORE": "8.3",
    "TOOL_6_FEATURES_PCT": "61", "TOOL_6_FEATURES_SCORE": "6.1",
    "TOOL_6_INT_PCT": "64", "TOOL_6_INT_SCORE": "6.4",
    "TOOL_6_SUPPORT_PCT": "73", "TOOL_6_SUPPORT_SCORE": "7.3",
    "TOOL_6_PRO_1": "Forever-free plan with unlimited contacts",
    "TOOL_6_PRO_2": "Built-in calling &amp; email sequencing",
    "TOOL_6_PRO_3": "Freddy AI included on all paid plans",
    "TOOL_6_CON_1": "Integration library lags well behind HubSpot",
    "TOOL_6_CON_2": "Reporting needs work on growth tiers",
    "TOOL_6_PRICE_LINE": "Free", "TOOL_6_PRICE_NOTE": "Paid from $9/user/mo",
    "TOOL_6_GO_LINK": "/go/freshsales",
    # ── Comparison table content ──
    "CMP_FEAT_FREE": "Free Plan", "CMP_FEAT_PRICE": "Starting Price",
    "CMP_FEAT_AI": "AI Assistant", "CMP_FEAT_EMAIL": "Email Marketing",
    "CMP_FEAT_INT": "Integrations", "CMP_FEAT_MOB": "Mobile App",
    "CMP_FEAT_FORE": "Forecasting", "CMP_FEAT_SETUP": "Setup Complexity",
    # Tool 1 comparison cells
    "C_T1_FREE": "&#10003; Unlimited", "C_T1_FREE_CLS": "cw",
    "C_T1_PRICE": "$15/user", "C_T1_AI": "ChatSpot AI", "C_T1_AI_CLS": "cw",
    "C_T1_EMAIL": "Built-in", "C_T1_EMAIL_CLS": "cw",
    "C_T1_INT": "", "C_T1_INT_CLS": "cw",
    "C_T1_MOB": "Excellent", "C_T1_MOB_CLS": "cw",
    "C_T1_FORE": "Mid tier+", "C_T1_FORE_CLS": "cm",
    "C_T1_SETUP": "Easy", "C_T1_SETUP_CLS": "cw",
    # Tool 2 comparison cells
    "C_T2_FREE": "&#10007;", "C_T2_FREE_CLS": "cl",
    "C_T2_PRICE": "$25/user", "C_T2_AI": "Einstein AI", "C_T2_AI_CLS": "cw",
    "C_T2_EMAIL": "Add-on ($$)", "C_T2_EMAIL_CLS": "cm",
    "C_T2_INT": "AppExchange", "C_T2_INT_CLS": "cw",
    "C_T2_MOB": "Good", "C_T2_MOB_CLS": "cm",
    "C_T2_FORE": "Best-in-class", "C_T2_FORE_CLS": "cw",
    "C_T2_SETUP": "Complex", "C_T2_SETUP_CLS": "cl",
    # Tool 3 comparison cells
    "C_T3_FREE": "&#10007;", "C_T3_FREE_CLS": "cl",
    "C_T3_PRICE": "$14/user", "C_T3_AI": "Basic", "C_T3_AI_CLS": "cm",
    "C_T3_EMAIL": "Campaigns add-on", "C_T3_EMAIL_CLS": "cm",
    "C_T3_INT": "400+", "C_T3_INT_CLS": "",
    "C_T3_MOB": "Excellent", "C_T3_MOB_CLS": "cw",
    "C_T3_FORE": "Good", "C_T3_FORE_CLS": "cm",
    "C_T3_SETUP": "Easy", "C_T3_SETUP_CLS": "cw",
    # Tool 4 comparison cells
    "C_T4_FREE": "Trial only", "C_T4_FREE_CLS": "cm",
    "C_T4_PRICE": "$12/seat", "C_T4_AI": "Automations", "C_T4_AI_CLS": "cm",
    "C_T4_EMAIL": "Basic", "C_T4_EMAIL_CLS": "",
    "C_T4_INT": "200+", "C_T4_INT_CLS": "",
    "C_T4_MOB": "Good", "C_T4_MOB_CLS": "cm",
    "C_T4_FORE": "Basic", "C_T4_FORE_CLS": "",
    "C_T4_SETUP": "Easy", "C_T4_SETUP_CLS": "cw",
    # Tool 5 comparison cells
    "C_T5_FREE": "&#10003; 3 users", "C_T5_FREE_CLS": "cw",
    "C_T5_PRICE": "$14/user", "C_T5_AI": "Zia AI", "C_T5_AI_CLS": "cw",
    "C_T5_EMAIL": "Built-in", "C_T5_EMAIL_CLS": "cw",
    "C_T5_INT": "800+", "C_T5_INT_CLS": "",
    "C_T5_MOB": "Good", "C_T5_MOB_CLS": "cm",
    "C_T5_FORE": "Good", "C_T5_FORE_CLS": "cm",
    "C_T5_SETUP": "Moderate", "C_T5_SETUP_CLS": "cm",
    # Tool 6 comparison cells
    "C_T6_FREE": "&#10003; Unlimited", "C_T6_FREE_CLS": "cw",
    "C_T6_PRICE": "$9/user", "C_T6_AI": "Freddy AI", "C_T6_AI_CLS": "cw",
    "C_T6_EMAIL": "Limited", "C_T6_EMAIL_CLS": "cm",
    "C_T6_INT": "200+", "C_T6_INT_CLS": "",
    "C_T6_MOB": "Good", "C_T6_MOB_CLS": "cm",
    "C_T6_FORE": "Basic", "C_T6_FORE_CLS": "",
    "C_T6_SETUP": "Easy", "C_T6_SETUP_CLS": "cw",
    # FAQs
    "FAQ_1_Q": "Which CRM is best for small businesses in 2026?",
    "FAQ_1_A": "HubSpot CRM is the best starting point — genuinely unlimited free tier, fast setup, strong email and deal tracking. For tight budgets, Freshsales ($9/user) or Zoho (free up to 3 users) are excellent alternatives.",
    "FAQ_2_Q": "What is the cheapest CRM with a free plan?",
    "FAQ_2_A": "HubSpot, Zoho CRM, and Freshsales all offer free plans. HubSpot's is the most generous — no seat cap, no contact limit.",
    "FAQ_3_Q": "Is Salesforce worth it for small teams?",
    "FAQ_3_A": "Rarely. Salesforce demands dedicated admin resources. True TCO is 2–3× the licence cost. HubSpot or Pipedrive will be faster and far cheaper for teams under 50 seats.",
    "FAQ_4_Q": "How often are these rankings updated?",
    "FAQ_4_A": "Pricing data is re-verified every Wednesday. Scores are reviewed quarterly or when a tool ships a significant update.",
    "FAQ_5_Q": "Can vendors pay to improve their ranking?",
    "FAQ_5_A": "No. Scores and rankings are finalised before any affiliate conversation. We may earn a commission if you click through — but this has zero bearing on ranking position.",
}

# ─── PRICING DEMO: HubSpot Pricing 2026 ─────────────────────────────────────
pricing_data = {
    "TOOL_NAME": "HubSpot",
    "META_DESCRIPTION": "HubSpot pricing 2026: all plans compared, hidden fees exposed, real cost at 1, 10, and 50 seats.",
    "CANONICAL_URL": "pages/hubspot-pricing-2026",
    "TOOL_LOGO_URL": "https://cdn.simpleicons.org/hubspot/ff7a59",
    "TOOL_GO_LINK": "/go/hubspot-crm",
    "TOOL_PAGE_URL": "/pages/best-hubspot-alternatives-2026",
    "TOOL_HISTORY_URL": "/pages/hubspot-pricing-history-2026",
    "VERIFIED_DATE": "June 2026",
    "STICKY_CTA_TEXT": "HubSpot has a free plan — try it before you pay anything.",
    "HIDDEN_COST_COUNT": "5",
    "HIDDEN_FEE_RISK_LEVEL": "Medium",
    "HIDDEN_FEE_RISK_NOTE": "Onboarding fees and Hub add-ons can triple your first-year cost",
    "PLAN_COUNT": "4",
    "PLAN_1_NAME": "Free", "PLAN_1_PRICE_MO": "$0", "PLAN_1_PRICE_ANNUAL": "$0",
    "PLAN_1_BEST_FOR": "Solo / exploring", "PLAN_1_USERS": "Unlimited",
    "PLAN_1_STORAGE": "Unlimited contacts", "PLAN_1_SUPPORT": "Community only",
    "PLAN_1_F1": "Contact management", "PLAN_1_F1_CLS": "cw",
    "PLAN_1_F2": "Deal pipeline", "PLAN_1_F2_CLS": "cw",
    "PLAN_1_F3": "Email automation", "PLAN_1_F3_CLS": "cl",
    "PLAN_2_NAME": "Starter", "PLAN_2_PRICE_MO": "$20/user", "PLAN_2_PRICE_ANNUAL": "$15/user",
    "PLAN_2_ANNUAL_SAVE": "Save 25% annually",
    "PLAN_2_BEST_FOR": "Small teams", "PLAN_2_USERS": "Unlimited",
    "PLAN_2_STORAGE": "Unlimited contacts", "PLAN_2_SUPPORT": "Email only",
    "PLAN_2_F1": "Email sequences (5/user)", "PLAN_2_F1_CLS": "cm",
    "PLAN_2_F2": "Simple automation", "PLAN_2_F2_CLS": "cw",
    "PLAN_2_F3": "Custom properties", "PLAN_2_F3_CLS": "cw",
    "PLAN_3_NAME": "Professional", "PLAN_3_PRICE_MO": "$890", "PLAN_3_PRICE_ANNUAL": "$800",
    "PLAN_3_BEST_FOR": "Growth teams", "PLAN_3_USERS": "5 min. seats",
    "PLAN_3_STORAGE": "Unlimited contacts", "PLAN_3_SUPPORT": "Phone + email",
    "PLAN_3_F1": "Full automation", "PLAN_3_F1_CLS": "cw",
    "PLAN_3_F2": "Custom reports", "PLAN_3_F2_CLS": "cw",
    "PLAN_3_F3": "A/B testing", "PLAN_3_F3_CLS": "cw",
    "PLAN_4_NAME": "Enterprise", "PLAN_4_PRICE_MO": "$3,600", "PLAN_4_PRICE_ANNUAL": "$3,200",
    "PLAN_4_BEST_FOR": "Large orgs", "PLAN_4_USERS": "10 min. seats",
    "PLAN_4_STORAGE": "Unlimited contacts", "PLAN_4_SUPPORT": "Priority + dedicated",
    "PLAN_4_F1": "Custom objects", "PLAN_4_F1_CLS": "cw",
    "PLAN_4_F2": "Hierarchical teams", "PLAN_4_F2_CLS": "cw",
    "PLAN_4_F3": "SSO + advanced security", "PLAN_4_F3_CLS": "cw",
    "CMP_FEAT_1": "Key features", "CMP_FEAT_2": "Users", "CMP_FEAT_3": "Support",
    "HIDDEN_COST_1_NAME": "Onboarding fee", "HIDDEN_COST_1_DESC": "$3,000+ mandatory for Professional and above — not optional, rarely disclosed on the pricing page.",
    "HIDDEN_COST_2_NAME": "Seat minimums", "HIDDEN_COST_2_DESC": "Professional requires 3 paid seats minimum — even if you only need 1 power user.",
    "HIDDEN_COST_3_NAME": "Annual contract lock-in", "HIDDEN_COST_3_DESC": "Monthly billing is available but costs ~25–30% more. Most buyers get locked in annually without realising.",
    "HIDDEN_COST_4_NAME": "Hub add-ons", "HIDDEN_COST_4_DESC": "Marketing, Sales, Service, and CMS Hubs are each billed separately. A full stack easily reaches $3,000+/mo.",
    "HIDDEN_COST_5_NAME": "Marketing contact tiers", "HIDDEN_COST_5_DESC": "Marketing Hub charges per marketing contact you email — a large list drives significant additional cost on top of seat pricing.",
    "SCENARIO_1_USERS": "1 user", "SCENARIO_1_COST": "$0/mo",
    "SCENARIO_1_PLAN": "Free Plan", "SCENARIO_1_PLAN_CLS": "v-value",
    "SCENARIO_1_BREAKDOWN": "Free CRM — unlimited contacts, basic pipeline, community support",
    "SCENARIO_2_USERS": "10 users", "SCENARIO_2_COST": "~$500/mo",
    "SCENARIO_2_PLAN": "Starter", "SCENARIO_2_PLAN_CLS": "v-visual",
    "SCENARIO_2_BREAKDOWN": "CRM + Marketing Starter, 10 seats, billed annually — onboarding N/A at this tier",
    "SCENARIO_3_USERS": "50 users", "SCENARIO_3_COST": "~$4,800/mo",
    "SCENARIO_3_PLAN": "Professional", "SCENARIO_3_PLAN_CLS": "v-ent",
    "SCENARIO_3_BREAKDOWN": "Professional tier, 50 seats, annual billing, mandatory onboarding $3k amortised — plus add-on Hubs",
    "ALT_1_NAME": "Salesforce", "ALT_1_URL": "/pages/salesforce-vs-hubspot", "ALT_1_PRICE": "From $25/user",
    "ALT_1_LOGO_URL": "https://cdn.simpleicons.org/salesforce/00a1e0",
    "ALT_2_NAME": "Pipedrive", "ALT_2_URL": "/pages/pipedrive-vs-hubspot", "ALT_2_PRICE": "From $14/user",
    "ALT_2_LOGO_URL": "https://cdn.simpleicons.org/pipedrive/1a73e8",
    "ALT_3_NAME": "Monday CRM", "ALT_3_URL": "/pages/monday-vs-hubspot", "ALT_3_PRICE": "From $12/seat",
    "ALT_3_LOGO_URL": "https://cdn.simpleicons.org/monday/f62b54",
    "ALT_4_NAME": "Zoho CRM", "ALT_4_URL": "/pages/zoho-vs-hubspot", "ALT_4_PRICE": "Free up to 3 users",
    "ALT_4_LOGO_URL": "https://cdn.simpleicons.org/zoho/e42527",
    "FAQ_1_Q": "Does HubSpot have a free plan?",
    "FAQ_1_A": "Yes — HubSpot CRM is free with no seat cap and no contact limit. The free plan includes deal pipeline, contact management, and basic email marketing.",
    "FAQ_2_Q": "How much does HubSpot actually cost for 10 users?",
    "FAQ_2_A": "For a team of 10 on Starter (CRM only), expect around $150/mo billed annually. Add Marketing Hub and you're looking at $400–800/mo depending on contact tier.",
    "FAQ_3_Q": "Is HubSpot's onboarding fee mandatory?",
    "FAQ_3_A": "Yes for Professional and Enterprise — HubSpot charges $3,000–$6,000 in mandatory onboarding fees. This is not optional and is rarely disclosed prominently.",
    "FAQ_4_Q": "Does HubSpot charge per contact?",
    "FAQ_4_A": "Marketing Hub charges per marketing contact. CRM contacts are unlimited on all plans. A large email list can significantly increase your Marketing Hub cost.",
    "FAQ_5_Q": "Is there a HubSpot discount for startups?",
    "FAQ_5_A": "Yes — HubSpot for Startups offers 30–90% off for qualifying startups under $2M ARR. Apply at hubspot.com/startups.",
}

# ─── REVIEW DEMO: NordVPN Review ────────────────────────────────────────────
review_data = {
    "TOOL_NAME": "NordVPN",
    "META_DESCRIPTION": "NordVPN review 2026: is it still the best VPN? Honest verdict on speed, privacy, price, and support.",
    "CANONICAL_URL": "pages/nordvpn-review-2026",
    "TOOL_LOGO_URL": "https://cdn.simpleicons.org/nordvpn/4687ff",
    "TOOL_GO_LINK": "/go/nordvpn",
    "TOOL_PRICING_URL": "/pages/nordvpn-pricing-2026",
    "VERIFIED_DATE": "June 2026", "VERIFIED_DATE_ISO": "2026-06-03",
    "HERO_LEAD": "We put NordVPN through 6 weeks of daily testing — speed, leaks, streaming, and support. Here's the honest verdict.",
    "OVERALL_SCORE": "9.2", "OVERALL_RING_CLASS": "sr-gold",
    "OVERALL_SCORE_OFFSET": "14.6", "OVERALL_SCORE_OFFSET_SM": "14.6",
    "VERDICT_ONELINER": "The gold standard for consumer VPNs — fast, private, and packed with features at a price that's hard to beat on a 2-year plan.",
    "VERDICT_HEADLINE": "Near-perfect for individuals and families",
    "VERDICT_BODY": "NordVPN earns its position as the most recommended consumer VPN in 2026. The 2-year plan is exceptional value — $2.99/mo for security that would cost 3× as much from a business VPN provider. If you're an individual or family, it's a near-no-brainer.",
    "VERDICT_SHORT": "Best buy for most people",
    "VERDICT_ICON": "&#9733;",
    "VERDICT_CTA_TEXT": "Try NordVPN Free for 30 Days →",
    "BEST_FOR": "Privacy-conscious users, streamers, remote workers, families",
    "BEST_FOR_SHORT": "Privacy &amp; streaming",
    "NOT_FOR": "Teams needing centralised billing or enterprise management",
    "FREE_PLAN_LABEL": "30-day money-back guarantee",
    "PRICE_FROM": "$2.99/mo",
    "PRICE_SUMMARY": "2-year plan: $71.76 upfront ($2.99/mo). Renews at $5.99/mo. Monthly billing: $12.99/mo.",
    "REVIEW_COUNT": "47",
    "REVIEW_SUMMARY": "Excellent",
    "PRO_1": "6,300+ servers across 111 countries",
    "PRO_2": "Verified no-logs policy (audited by Deloitte)",
    "PRO_3": "Threat Protection blocks malware &amp; trackers without VPN active",
    "PRO_4": "Meshnet — connect your own devices like a private LAN",
    "PRO_5": "10 simultaneous device connections on all plans",
    "CON_1": "Best price requires a 2-year upfront commitment",
    "CON_2": "No dedicated business management dashboard",
    "CON_3": "Speed can dip on congested servers at peak hours",
    "CON_4": "macOS app lacks some features vs Windows",
    "SCORE_EASE_PCT": "94", "SCORE_EASE": "9.4",
    "SCORE_VALUE_PCT": "91", "SCORE_VALUE": "9.1",
    "SCORE_FEATURES_PCT": "93", "SCORE_FEATURES": "9.3",
    "SCORE_INT_PCT": "85", "SCORE_INT": "8.5",
    "SCORE_SUPPORT_PCT": "88", "SCORE_SUPPORT": "8.8",
    "FAQ_1_Q": "Is NordVPN worth it in 2026?",
    "FAQ_1_A": "Yes — NordVPN remains the best all-round consumer VPN. Fast speeds, audited no-logs policy, and a feature set that beats most rivals at half the price.",
    "FAQ_2_Q": "How much does NordVPN cost?",
    "FAQ_2_A": "NordVPN's 2-year plan costs $2.99/mo ($71.76 upfront). Monthly billing costs $12.99/mo. The 2-year deal is the best value but requires commitment.",
    "FAQ_3_Q": "Does NordVPN keep logs?",
    "FAQ_3_A": "No — NordVPN has a verified no-logs policy, audited twice by Deloitte. They run on RAM-only servers in most locations, meaning no data can be stored.",
    "FAQ_4_Q": "Can I use NordVPN for streaming?",
    "FAQ_4_A": "Yes — NordVPN reliably unblocks Netflix (20+ libraries), BBC iPlayer, Disney+, and most major streaming platforms. SmartPlay technology handles routing automatically.",
    "FAQ_5_Q": "What is NordVPN's refund policy?",
    "FAQ_5_A": "NordVPN offers a 30-day money-back guarantee, no questions asked. Contact support within 30 days of purchase for a full refund.",
}

# ─── COUPON DEMO: NordVPN Coupon ─────────────────────────────────────────────
coupon_data = {
    "TOOL_NAME": "NordVPN",
    "META_DESCRIPTION": "NordVPN coupon codes 2026: get up to 73% off with our verified, working discount codes. Updated June 2026.",
    "CANONICAL_URL": "pages/nordvpn-coupon-2026",
    "TOOL_LOGO_URL": "https://cdn.simpleicons.org/nordvpn/4687ff",
    "TOOL_GO_LINK": "/go/nordvpn",
    "TOOL_PAGE_URL": "/pages/nordvpn-review-2026",
    "TOOL_PRICING_URL": "/pages/nordvpn-pricing-2026",
    "VERIFIED_DATE": "June 2026",
    "HERO_LEAD": "Every NordVPN discount verified manually as of June 2026. No fake countdowns. No expired codes.",
    "TOP_DEAL_PCT": "73",
    "TOP_DEAL_LABEL": "Best Deal Right Now",
    "TOP_DEAL_META": "73% off the 2-year plan — verified June 3, 2026",
    "NO_CODE_FALLBACK_TEXT": "No code needed — use our affiliate link and the discount applies automatically at checkout. If you want the exact price without a promo code, NordVPN's 2-year Basic plan is currently $2.99/mo ($71.76 billed upfront).",
    "DEAL_1_PCT": "73%", "DEAL_1_NAME": "2-Year Plan Deal",
    "DEAL_1_DESC": "Get 73% off the 2-year Basic plan — the biggest discount NordVPN offers. Includes 3 extra months free.",
    "DEAL_1_CODE": "SAASPARE73",
    "DEAL_1_VERIFIED_DATE": "Verified June 3, 2026",
    "DEAL_1_EXPIRY_NOTE": "No set expiry — NordVPN rolls this deal continuously",
    "DEAL_2_PCT": "59%", "DEAL_2_NAME": "1-Year Plan Discount",
    "DEAL_2_DESC": "Save 59% on a 1-year commitment. A good middle ground if you want a shorter lock-in period.",
    "DEAL_2_CODE": "NORDYR59",
    "DEAL_2_VERIFIED_DATE": "Verified June 1, 2026",
    "DEAL_2_EXPIRY_NOTE": "Available while promotional pricing lasts",
    "DEAL_3_PCT": "0%", "DEAL_3_NAME": "Monthly — No Discount",
    "DEAL_3_DESC": "Monthly billing at full price — $12.99/mo. No promo code available. Only choose this if you want to test without committing.",
    "DEAL_3_CODE": "No code needed",
    "DEAL_3_VERIFIED_DATE": "Verified May 2026",
    "DEAL_3_EXPIRY_NOTE": "Standard pricing — always available",
    "HOWTO_1_NAME": "Click our discount link",
    "HOWTO_1_DESC": "Use the button above to open NordVPN's pricing page with the discount pre-applied via our affiliate link.",
    "HOWTO_2_NAME": "Choose your plan",
    "HOWTO_2_DESC": "Select the 2-year plan for maximum savings. The discount is shown automatically at checkout — no code required.",
    "HOWTO_3_NAME": "Enter code if needed",
    "HOWTO_3_DESC": "If the discount isn't pre-applied, enter the promo code in the coupon field at the checkout screen.",
    "HOWTO_4_NAME": "Complete your purchase",
    "HOWTO_4_DESC": "Pay and get instant access to NordVPN on all your devices. You have 30 days to request a full refund, no questions asked.",
    "FAQ_1_Q": "Does NordVPN offer a student discount?",
    "FAQ_1_A": "NordVPN doesn't have a dedicated student program, but the 73% off 2-year deal is already exceptional value at under $3/mo.",
    "FAQ_2_Q": "Can I use a coupon on renewal?",
    "FAQ_2_A": "Coupons apply to new subscriptions only. Renewal pricing is higher — currently $5.99/mo on the 2-year plan. Set a calendar reminder to shop around before renewal.",
    "FAQ_3_Q": "What if the code doesn't work?",
    "FAQ_3_A": "Use our direct link above — the discount is applied automatically via our affiliate link, no code needed. Try clearing your browser cache if you have trouble.",
    "FAQ_4_Q": "Is there a NordVPN free trial?",
    "FAQ_4_A": "NordVPN doesn't offer a traditional free trial, but they have a 30-day money-back guarantee. Buy, test it fully for 30 days, and get a full refund if you're not happy.",
    "FAQ_5_Q": "What's the cheapest NordVPN plan?",
    "FAQ_5_A": "The 2-year Basic plan at $2.99/mo ($71.76 total) is the cheapest entry point. Complete plan adds Password Manager and Data Breach Scanner for $5.99/mo.",
}

# ─── FREE TRIAL DEMO: HubSpot Free Trial ────────────────────────────────────
trial_data = {
    "TOOL_NAME": "HubSpot",
    "META_DESCRIPTION": "How to get HubSpot's free trial in 2026 — what's included, what happens when it ends, and whether you need a credit card.",
    "CANONICAL_URL": "pages/hubspot-free-trial-2026",
    "TOOL_LOGO_URL": "https://cdn.simpleicons.org/hubspot/ff7a59",
    "TOOL_GO_LINK": "/go/hubspot-crm",
    "TOOL_PAGE_URL": "/pages/hubspot-review-2026",
    "TOOL_TRIAL_LINK": "/go/hubspot-crm",
    "VERIFIED_DATE": "June 2026",
    "HERO_LEAD": "HubSpot's free CRM is unlimited forever. Their Professional trial is 14 days with full access — no credit card required. Here's exactly how to get it.",
    "TRIAL_DAYS": "14",
    "TRIAL_CC_CLASS": "v-value",
    "TRIAL_CC_LABEL": "No credit card required",
    "TRIAL_CTA_NOTE": "Instant access. No payment required. Downgrade to free anytime.",
    "TRIAL_USERS": "Up to 5 users",
    "TRIAL_SUPPORT": "Chat + email",
    "TRIAL_PLAN_ACCESS": "Professional",
    "TRIAL_F1": "Email automation", "TRIAL_F1_CLS": "cw",
    "TRIAL_F2": "Custom reports", "TRIAL_F2_CLS": "cw",
    "TRIAL_F3": "A/B testing", "TRIAL_F3_CLS": "cw",
    "TRIAL_F4": "Sequences (unlimited)", "TRIAL_F4_CLS": "cw",
    "TRIAL_F5": "Forecasting tools", "TRIAL_F5_CLS": "cw",
    "PLAN_STARTER_NAME": "Starter",
    "STARTER_USERS": "Unlimited",
    "STARTER_SUPPORT": "Email only",
    "STARTER_PRICE": "From $15/user/mo",
    "STARTER_F1": "Email sequences (5/user)", "STARTER_F1_CLS": "cm",
    "STARTER_F2": "Basic automation", "STARTER_F2_CLS": "cw",
    "STARTER_F3": "Custom properties", "STARTER_F3_CLS": "cw",
    "STARTER_F4": "Basic reports", "STARTER_F4_CLS": "cw",
    "STARTER_F5": "No A/B testing", "STARTER_F5_CLS": "cl",
    "PLAN_PRO_NAME": "Professional",
    "PRO_USERS": "5 min seats",
    "PRO_SUPPORT": "Phone + email",
    "PRO_PRICE": "From $800/mo (annual)",
    "PRO_F1": "Full automation", "PRO_F1_CLS": "cw",
    "PRO_F2": "Custom reports", "PRO_F2_CLS": "cw",
    "PRO_F3": "A/B testing", "PRO_F3_CLS": "cw",
    "PRO_F4": "Sequences (unlimited)", "PRO_F4_CLS": "cw",
    "PRO_F5": "Forecasting", "PRO_F5_CLS": "cw",
    "FEAT_ROW_1": "Contact management", "FEAT_ROW_2": "Deal pipeline",
    "FEAT_ROW_3": "Email sequences", "FEAT_ROW_4": "Marketing automation",
    "FEAT_ROW_5": "Custom reports",
    "STEP_1_NAME": "Go to HubSpot.com",
    "STEP_1_DESC": "Click 'Get started free' on HubSpot's homepage or use the button above to go directly to signup.",
    "STEP_1_TIP": "Use our link to go straight to the pricing page — no hunting required.",
    "STEP_2_NAME": "Create your account",
    "STEP_2_DESC": "Enter your work email and set a password. HubSpot recommends a work email, but personal Gmail is accepted.",
    "STEP_2_TIP": "",
    "STEP_3_NAME": "Select a Hub to trial",
    "STEP_3_DESC": "Choose which Hub you want to trial — CRM, Marketing, Sales, or Service. Each has a separate 14-day trial window.",
    "STEP_3_TIP": "Start with CRM — it's free forever and gives the best product overview.",
    "STEP_4_NAME": "Activate your trial",
    "STEP_4_DESC": "HubSpot activates the Professional trial immediately. Full access to all features for 14 days, no payment required upfront.",
    "STEP_4_TIP": "",
    "WHAT_HAPPENS_1_TITLE": "Account stays active",
    "WHAT_HAPPENS_1_DESC": "Your HubSpot account doesn't disappear — it reverts to the Free plan. All your contacts and data are preserved.",
    "WHAT_HAPPENS_2_TITLE": "No auto-charge",
    "WHAT_HAPPENS_2_DESC": "Because no credit card is required for the free trial, you won't be charged automatically when it ends.",
    "WHAT_HAPPENS_3_TITLE": "Pro features lock",
    "WHAT_HAPPENS_3_DESC": "Workflows, sequences, and automation you built during the trial will pause. You'll need a paid plan to reactivate them.",
    "WHAT_HAPPENS_4_TITLE": "Data is retained",
    "WHAT_HAPPENS_4_DESC": "All contacts, deals, and notes remain accessible on the Free plan — nothing is deleted when the trial ends.",
    "FAQ_1_Q": "Does HubSpot free trial require a credit card?",
    "FAQ_1_A": "No — HubSpot's free trial requires only a work email. No payment details are collected upfront, so there's no risk of accidental charges.",
    "FAQ_2_Q": "How long is HubSpot's free trial?",
    "FAQ_2_A": "The Professional tier trial is 14 days. The free CRM plan is unlimited — you can use it forever at no cost.",
    "FAQ_3_Q": "Can I extend my HubSpot trial?",
    "FAQ_3_A": "In some cases yes — contact your HubSpot sales rep and ask for an extension. Extensions of 7–14 days are sometimes granted if you're actively evaluating.",
    "FAQ_4_Q": "What's the difference between HubSpot Free and the trial?",
    "FAQ_4_A": "The trial gives you full Professional access (automation, sequences, custom reports). The Free plan is the permanently free CRM with unlimited contacts but no automation.",
    "FAQ_5_Q": "Can I trial multiple HubSpot Hubs at once?",
    "FAQ_5_A": "Yes — you can activate trials for CRM, Marketing, Sales, and Service Hubs simultaneously. Each has its own 14-day window.",
}

# ─── PRICING HISTORY DEMO: Salesforce ────────────────────────────────────────
history_data = {
    "TOOL_NAME": "Salesforce",
    "META_DESCRIPTION": "Salesforce pricing history 2026: every price change tracked since 2023, true-cost analysis, and when to buy.",
    "CANONICAL_URL": "pages/salesforce-pricing-history-2026",
    "TOOL_LOGO_URL": "https://cdn.simpleicons.org/salesforce/00a1e0",
    "TOOL_GO_LINK": "/go/salesforce",
    "TOOL_PAGE_URL": "/pages/best-salesforce-alternatives-2026",
    "TOOL_PRICING_URL": "/pages/salesforce-pricing-2026",
    "TOOL_REVIEW_URL": "/pages/salesforce-review-2026",
    "TOOL_TRIAL_LINK": "/go/salesforce",
    "TOOL_COUPON_URL": "/pages/salesforce-coupon-2026",
    "VERIFIED_DATE": "June 2026",
    "HERO_LEAD": "Five documented price changes since 2023. Advertised price vs. what you actually pay are very different numbers. Here's every change tracked.",
    "PRICE_CHANGES_COUNT": "5",
    "PRICE_CHANGE_NOTE": "Most recent change: June 2024 — +9% across Enterprise and Unlimited tiers",
    "SCORECARD_ADVERTISED": "$25/user/mo",
    "SCORECARD_ADVERTISED_SUB": "Starter Suite — list price",
    "SCORECARD_TRUE_COST": "$75–180/user/mo",
    "SCORECARD_TRUE_COST_SUB": "Including admin, onboarding &amp; add-ons",
    "SCORECARD_RISK_LEVEL": "High",
    "SCORECARD_RISK_CLASS": "v-sales",
    "SCORECARD_RISK_SUB": "Multiple hidden fee vectors",
    "SCORECARD_VERIFIED_SUB": "Verified June 3, 2026",
    "TL_1_DATE": "Jun 2024", "TL_1_HEADLINE": "+9% price increase — Enterprise &amp; Unlimited",
    "TL_1_DETAIL": "Enterprise raised from $165 to $180/user/mo. Unlimited from $330 to $360/user/mo. First across-the-board increase since 2020.",
    "TL_1_BADGE_CLASS": "v-sales", "TL_1_DOT_CLASS": "dot-red",
    "TL_1_ICON": "&#9650;", "TL_1_CHANGE_LABEL": "Price increase", "TL_1_SOURCE": "Salesforce renewal notices",
    "TL_2_DATE": "Mar 2024", "TL_2_HEADLINE": "Einstein AI bundled into Unlimited+",
    "TL_2_DETAIL": "Einstein GPT features bundled into new Unlimited+ tier at $500/user/mo. Customers on Unlimited pushed toward the higher tier for AI features.",
    "TL_2_BADGE_CLASS": "v-visual", "TL_2_DOT_CLASS": "dot-amber",
    "TL_2_ICON": "&#9656;", "TL_2_CHANGE_LABEL": "New tier added", "TL_2_SOURCE": "Salesforce blog",
    "TL_3_DATE": "Jan 2024", "TL_3_HEADLINE": "Essentials plan retired — replaced by Starter Suite",
    "TL_3_DETAIL": "Essentials tier removed. Replacement Starter Suite carries the same $25/user price but with mandatory annual contract and fewer features.",
    "TL_3_BADGE_CLASS": "v-sales", "TL_3_DOT_CLASS": "dot-red",
    "TL_3_ICON": "&#9650;", "TL_3_CHANGE_LABEL": "Plan retired", "TL_3_SOURCE": "Salesforce pricing page",
    "TL_4_DATE": "Aug 2023", "TL_4_HEADLINE": "API access restricted to Enterprise+",
    "TL_4_DETAIL": "API access removed from Professional tier for new purchases. Existing Professional customers grandfathered but warned of future changes.",
    "TL_4_BADGE_CLASS": "v-smb", "TL_4_DOT_CLASS": "dot-amber",
    "TL_4_ICON": "&#9656;", "TL_4_CHANGE_LABEL": "Feature removed", "TL_4_SOURCE": "Salesforce developer docs",
    "TL_5_DATE": "Jan 2023", "TL_5_HEADLINE": "Monthly billing removed for most tiers",
    "TL_5_DETAIL": "Monthly billing removed for Professional and Enterprise except through specific sales channels. Annual commit became the default for most buyers.",
    "TL_5_BADGE_CLASS": "v-sales", "TL_5_DOT_CLASS": "dot-red",
    "TL_5_ICON": "&#9650;", "TL_5_CHANGE_LABEL": "Billing change", "TL_5_SOURCE": "Salesforce pricing FAQ",
    "BUYER_STARTUP_REC": "Use HubSpot Free instead",
    "BUYER_STARTUP_WHY": "Salesforce TCO destroys startup budgets. HubSpot CRM is free, unlimited contacts, zero implementation cost.",
    "BUYER_STARTUP_CTA": "See HubSpot alternatives",
    "BUYER_STARTUP_LINK": "/pages/best-hubspot-alternatives-2026",
    "BUYER_SMB_REC": "Starter Suite — if you have an admin",
    "BUYER_SMB_WHY": "$25/user works at 10–30 seats if you budget 3× list price for true TCO including setup and training.",
    "BUYER_SMB_CTA": "Compare SMB CRMs",
    "BUYER_SMB_LINK": "/pages/best-crm-software-2026",
    "BUYER_ENT_REC": "Negotiate aggressively",
    "BUYER_ENT_WHY": "Enterprise list prices are rarely paid. 30–40% discounts are available for multi-year commits, especially in Q4 (Salesforce's fiscal year end).",
    "BUYER_ENT_CTA": "See enterprise comparison",
    "BUYER_ENT_LINK": "/pages/salesforce-vs-hubspot",
    "FAQ_1_Q": "Has Salesforce raised prices recently?",
    "FAQ_1_A": "Yes — Salesforce raised Enterprise and Unlimited pricing by 9% in June 2024, the first significant increase since 2020. They also bundled AI features into higher tiers, effectively increasing costs for many customers.",
    "FAQ_2_Q": "What does Salesforce really cost for 10 users?",
    "FAQ_2_A": "On Starter Suite at $25/user/mo, 10 users costs $3,000/year. Add implementation ($5,000–20,000), admin (0.5–1 FTE), and add-ons — you're looking at $20,000–50,000/year total.",
    "FAQ_3_Q": "Can you negotiate Salesforce pricing?",
    "FAQ_3_A": "Yes — significantly. Salesforce salespeople have large discount authority, especially at end of quarter. 20–40% off list price is achievable for multi-year deals.",
    "FAQ_4_Q": "Is there a cheaper alternative to Salesforce?",
    "FAQ_4_A": "HubSpot Professional at $890/mo for 5 users is ~70% cheaper than equivalent Salesforce Enterprise. Pipedrive is even cheaper at $14–99/user/mo with no hidden implementation costs.",
    "FAQ_5_Q": "Does Salesforce have a free plan?",
    "FAQ_5_A": "No — Salesforce's cheapest option is Starter Suite at $25/user/mo, billed annually. There is no free tier.",
}

# ─── Write demos ─────────────────────────────────────────────────────────────
demos = [
    ("best-of-demo.html",        "best-of.html",        best_of_data),
    ("pricing-demo.html",        "pricing.html",        pricing_data),
    ("review-demo.html",         "review.html",         review_data),
    ("coupon-demo.html",         "coupon.html",         coupon_data),
    ("free-trial-demo.html",     "free-trial.html",     trial_data),
    ("pricing-history-demo.html","pricing-history.html",history_data),
]

total_unfilled = 0
for demo_name, template_name, data in demos:
    template_path = TEMPLATES / template_name
    html = fill(template_path, data)
    remaining = re.findall(r'\{\{[A-Z0-9_]+\}\}', html)
    unfilled = len(remaining)
    total_unfilled += unfilled
    out_path = DEMO_DIR / demo_name
    out_path.write_text(html, encoding="utf-8")
    if unfilled == 0:
        print(f"[OK] {demo_name}")
    else:
        print(f"[WARN {unfilled} unfilled] {demo_name}: {set(remaining)}")

print(f"\nTotal unfilled: {total_unfilled}")
print(f"Demos: {DEMO_DIR}")
