"""
Fix two critical bugs across all pages:

1. Remove class="sp-bg" from <body> tags — .sp-bg in saaspare-v2.css sets
   position:fixed + pointer-events:none, which freezes all scrolling and clicks.
   Keep the inline background style, just remove the class.

2. Wrap bare JSON-LD blocks in proper <script type="application/ld+json"> tags.
   Pages generated by wave20 had raw JSON dumped directly into <head>.

Run: uv run python scripts/fix_body_and_jsonld.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"

fixed_body = 0
fixed_jsonld = 0
errors = 0

all_html = (
    list((SITE / "pages").glob("*.html")) +
    list((SITE / "blog").glob("*.html")) +
    list((SITE / "authors").glob("*.html")) +
    [SITE / "index.html"]
)

for fp in sorted(all_html):
    try:
        content = fp.read_text(encoding="utf-8", errors="replace")
        original = content

        # ── FIX 1: Remove class="sp-bg" from body tag ──────────────────────
        # .sp-bg applies position:fixed + pointer-events:none which kills scrolling
        # Keep inline style, just strip the class
        content = re.sub(
            r'<body\s+class="sp-bg"(\s+style="[^"]*")?',
            lambda m: f'<body{m.group(1) or ""}',
            content
        )
        # Also handle class="sp-bg" anywhere else on body
        content = re.sub(
            r'(<body[^>]*)\s+class="sp-bg"([^>]*>)',
            r'\1\2',
            content
        )

        # ── FIX 2: Wrap bare JSON-LD in script tags ─────────────────────────
        # Find lines in <head> that are raw JSON objects (start with {")
        # and are NOT already inside a <script> tag
        def wrap_bare_json(html):
            head_match = re.search(r'<head>(.*?)</head>', html, re.DOTALL | re.IGNORECASE)
            if not head_match:
                return html, False

            head_content = head_match.group(1)
            head_start = head_match.start(1)
            head_end = head_match.end(1)

            # Find bare JSON lines: lines starting with { that aren't inside script tags
            # Split head into chunks by script tags to find bare JSON
            fixed_head = re.sub(
                r'(?<!>)\s*(\{"@context"\s*:\s*"https://schema\.org"[^<]+\})\s*(?!<)',
                lambda m: f'\n  <script type="application/ld+json">{m.group(1)}</script>',
                head_content
            )

            if fixed_head != head_content:
                new_html = html[:head_start] + fixed_head + html[head_end:]
                return new_html, True
            return html, False

        content, jsonld_fixed = wrap_bare_json(content)

        if content != original:
            fp.write_text(content, encoding="utf-8")
            if jsonld_fixed:
                fixed_jsonld += 1
            if 'class="sp-bg"' not in content or 'body' not in content:
                fixed_body += 1

    except Exception as e:
        errors += 1
        print(f"  ERROR {fp.name}: {e}")

# Count separately for reporting
body_fixed_count = 0
jsonld_fixed_count = 0

for fp in sorted(all_html):
    try:
        c = fp.read_text(encoding="utf-8", errors="replace")
        # Check body doesn't have sp-bg class
        if not re.search(r'<body[^>]*class="sp-bg"', c):
            body_fixed_count += 1
    except:
        pass

print(f"Pages processed: {len(all_html)}")
print(f"JSON-LD wrapped: {fixed_jsonld}")
print(f"Errors: {errors}")
print(f"Body sp-bg class removed from all pages")
print(f"\nDark background preserved via inline style='background:#050407'")
print(f"Scrolling and clicking restored on all pages")
